### ISSUE TITLE
Copybook Support

### ISSUE THREAD

**Issue by jellypuno** [BroadcomMFD/code4z#1]
> Copybook path must be defined as "COPYBOOKS" folder in current workspace (required for copybook support)

TIL that the Cobol LSP has a copybook support. Are there any documentations for this one? I'm lost on how to set it up.

Also, does this work if I have the copybooks in mainframe or do I have to download them first  in mt PC?

**Comment by sergiuilie** [comment]
Hello @jellypuno, I will be glad to update the documentation based on your user experience.

About the second question 
> Also, does this work if I have the copybooks in mainframe or do I have to download them first in mt PC?

Answer: No, currently we do not support direct interaction with mainframe so you will have to download them manually.

If there is another issue could you please open it on our LSP repository under Eclipse Foundation.
Thank you

[LSP4COBOL REPOSITORY](https://github.com/eclipse/che-che4z-lsp-for-cobol)

**Comment by gbegicw** [comment]
Zowe Explorer assists with direct interaction with the Mainframe. Check this page for example use cases: [Zowe Explorer]( https://marketplace.visualstudio.com/items?itemName=Zowe.vscode-extension-for-zowe)

Zowe Explorer is included in the Code4Z stack.
