### ISSUE TITLE
Add a License to your VS Code Extension

### ISSUE THREAD

**Issue by spoenemann** [BroadcomMFD/code4z#26]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please add a license to your extension and upload a new version **as early as possible before January 15, 2021**. To include a license with the extension, add a `license` field with the license identifier (if applicable) in the package.json and add a LICENSE file with the full license text.

Regrettably if this is not done by that date, extension versions that have no license will be deleted. Of course you can publish them again with a license at a later date.

Useful links:
[Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf)
[Eclipse Foundation Open VSX Registry Frequently Asked Questions (FAQ)](https://www.eclipse.org/legal/open-vsx-registry-faq/) 

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

**Comment by dezkolakatus** [comment]
> Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please add a license to your extension and upload a new version **as early as possible before January 15, 2021**. To include a license with the extension, add a `license` field with the license identifier (if applicable) in the package.json and add a LICENSE file with the full license text.
> 
> Regrettably if this is not done by that date, extension versions that have no license will be deleted. Of course you can publish them again with a license at a later date.
> 
> Useful links:
> [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf)
> [Eclipse Foundation Open VSX Registry Frequently Asked Questions (FAQ)](https://www.eclipse.org/legal/open-vsx-registry-faq/)
> 
> More details are in these recent blog posts:
> https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
> https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry



> Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please add a license to your extension and upload a new version **as early as possible before January 15, 2021**. To include a license with the extension, add a `license` field with the license identifier (if applicable) in the package.json and add a LICENSE file with the full license text.
> 
> Regrettably if this is not done by that date, extension versions that have no license will be deleted. Of course you can publish them again with a license at a later date.
> 
> Useful links:
> [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf)
> [Eclipse Foundation Open VSX Registry Frequently Asked Questions (FAQ)](https://www.eclipse.org/legal/open-vsx-registry-faq/)
> 
> More details are in these recent blog posts:
> https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
> https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Hi Miro, 

just to make sure. code4z is pack of extensions, is not extension it self. It is still required to have own license? 

thx,

**Comment by spoenemann** [comment]
AFAIK yes. Since an extension pack does not contain any code, choosing [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.en) or similar might be more appropriate than MIT, but that's up to you.

**Comment by zimlu02** [comment]
Updated. Just on time :-D
Thank you @spoenemann for the heads up!

**Comment by spoenemann** [comment]
Great! @zimlu02 could you publish a new version? We will have to delete the older versions with no license from the registry.

**Comment by zimlu02** [comment]
> Great! @zimlu02 could you publish a new version? We will have to delete the older versions with no license from the registry.

But the new version 1.1.7 is already published.

**Comment by spoenemann** [comment]
I see, thanks!
